version: 2

project_name: progressdb

builds:
  - id: progressdb
    main: ./server/cmd/progressdb
    binary: progressdb
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.buildDate={{ .Date }}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - progressdb
    files:
      - LICENSE.md
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    name: "{{ if .Tag }}{{ .Tag }}{{ else }}v{{ .Version }}{{ end }}"