server:
  address: "0.0.0.0"
  port: 8080
  db_path: "./database"
  tls:
    cert_file: ""
    key_file: ""

security:
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "http://127.0.0.1:3000"
  rate_limit:
    rps: 10
    burst: 20
  # ip_whitelist:
    # - "127.0.0.1"
    # - "::1"
  api_keys:
    backend: ["sk_example"]
    frontend: ["pk_example"]
    admin: ["admin_example"]
  encryption:
    use: true
    fields: []
  kms:
    endpoint: ""
    data_dir: ""
    binary: ""
    master_key_file: ""
    master_key_hex: "7d2d7bd0f14a52e270b5cf39821c68eea09bcc50809d670a9ee27a6f49fd0160"

logging:
  level: "info"

