server:
  address: "0.0.0.0"
  port: 8080
  db_path: "./database"
  tls:
    cert_file: ""
    key_file: ""

security:
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "http://127.0.0.1:3000"
  rate_limit:
    rps: 10
    burst: 20
  ip_whitelist:
    - "127.0.0.1"
  api_keys:
    backend: ["sk_example"]
    frontend: ["pk_example"]
    admin: ["admin_example"]
  encryption:
    use: true
    fields: []
  kms:
    endpoint: ""
    data_dir: ""
    binary: ""
    master_key_file: ""
    master_key_hex: "bcd68c14b0c3edfdba2e3d43163fd660fd0a752ba49aa58802c1fca17438a2d3"

logging:
  level: "info"

