name: Release via goreleaser

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write   # Required to upload release assets

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Docker Hub credentials
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          # GHCR: use current actor + GITHUB_TOKEN for authentication
          CR_USERNAME: ${{ github.actor }}
          CR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
