name: CI - Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Unit & Package Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ${{ github.workspace }}/.gocache
            ~/.cache/go-mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Run unit tests
        run: |
          chmod +x scripts/test.sh || true
          ./scripts/test.sh

  e2e:
    name: E2E Tests (main only)
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ${{ github.workspace }}/.gocache
            ~/.cache/go-mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-e2e
      - name: Build server binary and run E2E
        run: |
          chmod +x scripts/test-e2e.sh || true
          ./scripts/test-e2e.sh

