name: test-node-sdk

on:
  push:
    branches: [ main ]
    paths:
      - 'clients/sdk/backend/nodejs/**'
  pull_request:
    paths:
      - 'clients/sdk/backend/nodejs/**'

jobs:
  node-sdk:
    name: test-node-sdk
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: clients/sdk/backend/nodejs
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install & Test
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
          npm test || true
