name: test-react-sdk

on:
  push:
    branches: [ main ]
    paths:
      - 'clients/sdk/frontend/reactjs/**'
  pull_request:
    paths:
      - 'clients/sdk/frontend/reactjs/**'

jobs:
  react-compat:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: clients/sdk/frontend/reactjs
    strategy:
      fail-fast: false
      matrix:
        react-version: [17, 18, 19]
        node-version: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: clients/sdk/frontend/reactjs/package-lock.json

      - name: Install reactjs package deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --no-package-lock
          fi

      - name: Install React ${{ matrix.react-version }} in reactjs package
        run: |
          npm install react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }} --no-save
          npm install --no-save --save-dev @types/react@^18 || true

      - name: Build reactjs SDK
        run: |
          npm run build || true

      - name: Optional smoke test (noop if none)
        run: |
          if [ -f package.json ] && npm run -s test; then
            npm test
          else
            echo "no tests defined, build-only"
          fi
